### ISSUE TITLE
No Data ? 

### ISSUE THREAD

**Issue by gumush** [anaramirli/predict-soccer-ball-location#2]
Sample data not available to test. 
Could you upload the data folder ?

**Comment by anaramirli** [comment]
I'm sorry for the late reply!

I just added the train and test sets. You can find them in the src/dataset. Files were too large, so I've compressed them.

You can download it from github or directly download by running this :
```
wget  https://github.com/anaramirli/predict-soccer-ball-location/raw/master/src/dataset/(train%26test-csv).zip
```

I've added new features to the dataset as well. You can find detailed info on data features on feature_generation.ipynb
